# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

target 'JPVideoPlayerDemo_swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JPVideoPlayerDemo_swift

pod 'JPVideoPlayer', '~> 2.0.3’

end
